---
# This Playbook deploys OpenLDAP

- hosts: ldap
  user: root
  sudo: false
  vars_files:
    - defaults/main.yml
  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
