---
# This Playbook deploys OpenLDAP

- hosts: ldap
  user: $global_user
  sudo: $global_use_sudo
  vars_files:
    - vars/main.yml
    - vars/private.yml
  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
