---

- name: Make an ansible directory for remembering what we previously run
  file: path=$ldap_done_dir state=directory owner=root group=root
  tags: 
    - ldap
    - auth

- name: install ldap packages
  apt: pkg=$item state=installed
  with_items:
    - slapd 
    - ldap-utils
    - ldapscripts 
  tags: 
    - ldap
    - auth

- name: Configure slapd
  dpkg_reconfigure: pkg=slapd answers='$FILE(files/dpkg-reconfigure/slapd)'

- include: load-schema.yml

- name: ensure ldapscripts.conf exists
  template: src=templates/etc/ldapscripts/ldapscripts.conf.j2 dest=/etc/ldapscripts/ldapscripts.conf owner=root group=root
  tags: 
    - ldap
    - auth

- name: ensure ldap.secret exists
  template: src=templates/etc/ldap.secret.j2 dest=/etc/ldap.secret owner=root group=root mode=0400
  tags: 
    - ldap
    - auth

- name: ensure domainadmins exists
  template: src=templates/etc/sudoers.d/domainadmins dest=/etc/sudoers.d/domainadmins owner=root group=root mode=0440
  tags: 
    - ldap
    - auth

# This is really goofy but editing the secrets file in vims leaves an extra space at the end. Not sure what all editors do this
# If your editor does not do this then this command will mess up your file.
- name: ensure ldap.secret has no trailing space
  command: truncate --size $ldapPasswordSize /etc/ldap.secret
