---

- name: ldap | debconf for slapd
  debconf: name=slapd question='slapd/no_configuration' value='false' vtype='boolean'

- name: ldap | debconf for slapd
  debconf: name=slapd question='slapd/domain' value='{{ldap_domain}}' vtype='string'

- name: ldap | debconf for slapd
  debconf: name=slapd question='shared/organization' value='{{ldap_org}}' vtype='string'

- name: ldap | debconf for slapd
  debconf: name=slapd question='slapd/password1' value='{{ldap_password}}' vtype='password'

- name: ldap | debconf for slapd
  debconf: name=slapd question='slapd/password2' value='{{ldap_password}}' vtype='password'

- name: ldap | debconf for slapd
  debconf: name=slapd question='slapd/backend' value='MDB' vtype='select'

- name: ldap | debconf for slapd
  debconf: name=slapd question='slapd/purge_database' value='false' vtype='boolean'

- name: ldap | debconf for slapd
  debconf: name=slapd question='slapd/move_old_database' value='true' vtype='boolean'

- name: ldap | debconf for slapd
  debconf: name=slapd question='slapd/allow_ldap_v2' value='false' vtype='boolean'

- name: ldap | install ldap packages
  apt: pkg={{item}} state=installed
  with_items:
    - slapd 
    - ldap-utils
  tags: 
    - ldap
    - auth

- name: ldap | Copy over the create users and group ldif 
  template: src=create_users_and_groups.ldif.j2 dest=/tmp/create_users_and_groups.ldif owner=root group=root
  when: ldap_include_create_user_and_groups
  tags: 
    - ldap 
    - auth 

- name: ldap | Install users and groups 
  shell: ldapadd -w {{ldap_password}} -x -D cn=admin,{{ldap_dc}} -f create_users_and_groups.ldif chdir=/tmp
  when: ldap_include_create_user_and_groups
  tags: 
    - ldap 
    - auth

- name: ldap | ensure ldap.conf exists
  template: src=ldap.conf.j2 dest=/etc/ldap/ldap.conf owner=root group=root
  tags: 
    - ldap
    - auth

- name: ldap | ensure ldap.secret exists
  template: src=ldap.secret.j2 dest=/etc/ldap/ldap.secret owner=root group=root mode=0400
  tags: 
    - ldap
    - auth
